model:
  checkpoint: ./pretrained_models/pretrained_diffusion.pt
  force_model_type: diffdynamic
  use_grad_fusion: true
  grad_fusion_lambda:
    mode: quadratic
    start: 1
    end: 0
    power: 2
sample:
  seed: 2021
  mode: dynamic
  num_steps: 1000
  sample_num_atoms: prior
  center_pos_mode: protein
  pos_only: false
  dynamic:
    method: legacy
    time_boundary: 650
    skip_refine: false
    large_step:
      batch_size: 5
      n_repeat: 1
      schedule: lambda
      lambda_coeff_a: 58
      lambda_coeff_b: 20
      linear_step_lower: 15
      linear_step_upper: 15
      step_size: 0.33
      stride: 15
      noise_scale: 0.1
      use_adaptive_step: true
      use_time_scale: false
    selector:
      enable_selection: false
      selection_time: 250
      top_percent: 0.3
      top_n: 20
      min_sa: 0.1
      min_qed: 0.1
      qed_weight: 1
      sa_weight: 1
    prudent:
      enable: false
    refine:
      n_sampling: 1
      cycles: 1
      schedule: lambda
      lambda_coeff_a: 60
      lambda_coeff_b: 5
      linear_step_lower: 3
      linear_step_upper: 8
      step_size: 0.47
      stride: 5
      time_lower: 0
      noise_scale: 0.05
      use_adaptive_step: true
      use_time_scale: false
      max_grad_fusion_iterations: 15
  optimization:
    enable: false
  scaffold:
    enable: true
    mode: grow
    after_dynamic: false
    save_dynamic_before_scaffold: true
    optimization_style_naming: true
    scaffold_source: auto_murcko
    fix_scaffold_pos: true
    fix_scaffold_type: true
    schedule: lambda
    use_with_noise: true
    use_adaptive_step: true
    use_time_scale: false
    qed_weight: 1
    sa_weight: 1
    diversity_weight: 0.5
    rmsd_penalty_weight: 0
    min_qed: 0.15
    min_sa: 0.15
    keep_original: true
    filter_incomplete: true
    diversity_filter:
      enable: true
      max_tanimoto: 0.9
      fingerprint_radius: 2
      fingerprint_nbits: 2048
    grow:
      n_extra_mode: pocket_prior
      n_extra_fixed: 8
      n_extra_min: 3
      n_extra_max: 20
      n_extra_min_clamp: 1
      n_extra_max_clamp: 45
      num_samples: 5
      start_t: 416
      stride: 15
      step_size: 0.23562275268038252
      lambda_coeff_a: 33
      lambda_coeff_b: 13
      min_qed: 0.2
      min_sa: 0.2
      filter_incomplete: false
  targetdiff_baseline_refine:
    enable: false
  pre_docking:
    etkdg_reembed: false
    mmff_minimize: false
    mmff_max_iters: 2000
    use_uff_fallback: false
  step_trajectory_save:
    enable: false
